import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import AddBootstrap from "./AddBootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LLM - RAG",
  description: "Generated by create next app", 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </head>
      <body className={inter.className}>
        <AddBootstrap/>
        {children}</body>
    </html>
  );
}
